import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {sha256Hex,readSetting} from '../functions/lib/security.js';
import {onRequestPut as setAccess,onRequestGet as getAccess} from '../functions/api/admin/cv-access.js';
import {onRequestPost as revoke} from '../functions/api/admin/cv-access/revoke.js';
import {onRequestPost as unlock} from '../functions/api/cv/unlock.js';
import {onRequestGet as frenchCV} from '../functions/api/cv.js';
import {onRequestGet as englishCV} from '../functions/api/cv/en.js';
import {onRequestPut as putPhoto,onRequestPatch as patchPhoto,onRequestDelete as deletePhoto} from '../functions/api/admin/media/[key].js';
import {onRequestGet as publicPhoto} from '../functions/api/media.js';
import {onRequestPut as putCep,onRequestDelete as deleteCep} from '../functions/api/admin/cep.js';
import {onRequestPut as setCep} from '../functions/api/admin/cep/settings.js';
import {onRequestGet as publicCep} from '../functions/api/cep.js';
import {onRequestPut as publication} from '../functions/api/admin/publication.js';
import {onRequestGet as exportConfig} from '../functions/api/admin/export.js';
import {imageType} from '../functions/lib/media.js';
import {applyPresentation} from '../functions/lib/presentation.js';
import {onRequest as middleware} from '../functions/_middleware.js';
const origin='https://portfolio.example';
const schema=readFileSync(new URL('../schema.sql',import.meta.url),'utf8');
async function fixture(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(schema);sqlite.prepare("UPDATE settings SET value='true' WHERE key='site_public'").run();
 sqlite.prepare('INSERT INTO admin_sessions VALUES(?,?,?)').run(await sha256Hex('session-v8'),Math.floor(Date.now()/1000)+3600,1);
 const DB={prepare(sql){const st=sqlite.prepare(sql);let args=[];return{bind(...v){args=v;return this;},async first(){return st.get(...args)||null;},async all(){return{results:st.all(...args)};},async run(){return st.run(...args);}}}};
 const files=new Map();const CV_BUCKET={async get(k){const x=files.get(k);return x?{body:x.bytes,writeHttpMetadata(){}}:null;},async head(k){const x=files.get(k);return x?{size:x.bytes.length}:null;},async put(k,bytes,meta){files.set(k,{bytes:new Uint8Array(bytes),meta});},async delete(k){files.delete(k);}};
 const ASSETS={async fetch(){return new Response('static fallback',{status:200,headers:{'Content-Type':'image/webp'}});}};
 return {sqlite,files,env:{DB,CV_BUCKET,ASSETS,SESSION_SECRET:'test-v8-secret'}};
}
function req(path,method='GET',body,admin=false,cookie=''){const headers={Origin:origin,...(admin?{Cookie:'__Host-pm_admin=session-v8'}:{}),...(cookie?{Cookie:cookie}:{})};let payload;if(body instanceof FormData){payload=body;}else if(body!==undefined){headers['Content-Type']='application/json';payload=JSON.stringify(body);}return new Request(origin+path,{method,headers,...(payload?{body:payload}:{})});}
const pdf=new File([new Uint8Array([37,80,68,70,45,49,46,55])],'cep.pdf',{type:'application/pdf'});
const jpeg=new File([new Uint8Array([255,216,255,224,1])],'photo.jpg',{type:'image/jpeg'});
const png=new Uint8Array([137,80,78,71,13,10,26,10,1]);
const webp=new Uint8Array([82,73,70,70,0,0,0,0,87,69,66,80]);
test('V8 migration is idempotent and leaves V7 records intact',async()=>{const {sqlite}=await fixture();sqlite.prepare("UPDATE settings SET value='https://www.linkedin.com/in/example' WHERE key='linkedin_url'").run();const migration=readFileSync(new URL('../migrations/0008_career_media_cv.sql',import.meta.url),'utf8');sqlite.exec(migration);sqlite.exec(migration);assert.equal(sqlite.prepare("SELECT value FROM settings WHERE key='linkedin_url'").get().value,'https://www.linkedin.com/in/example');for(const name of ['media_overrides','cv_access_attempts','publication_flags','contact_messages','content_overrides'])assert.ok(sqlite.prepare("SELECT name FROM sqlite_master WHERE name=?").get(name));});
test('FR/EN project texts, photo slots, dialogue and initial hidden publication',()=>{const fr=readFileSync(new URL('../index.html',import.meta.url),'utf8');const en=readFileSync(new URL('../en/index.html',import.meta.url),'utf8');for(const [source,language] of [[fr,'fr'],[en,'en']]){assert.match(source,/data-content-key="project\.timeline\.step_2\.text"/);assert.match(source,/data-content-key="project\.international_detail\.country"/);assert.match(source,/data-publication-section="scenario_a" hidden/);assert.match(source,/data-publication-section="international_detail" hidden/);assert.equal((source.match(/data-media-key=/g)||[]).length,8);assert.match(source,new RegExp(`<html lang="${language}"`));assert.match(source,/id="cv-access-dialog"/);}});
test('CV defaults open; code gates both routes, expires, revokes, and resists brute force',async()=>{const {env,files,sqlite}=await fixture();for(const k of ['cv-pm-systems-engineering.pdf','cv-pm-systems-engineering-en.pdf'])files.set(k,{bytes:new Uint8Array([37,80,68,70,45])});sqlite.prepare("UPDATE settings SET value='true' WHERE key IN ('cv_available','cv_en_available')").run();assert.equal((await frenchCV({request:req('/api/cv'),env})).status,200);assert.equal((await englishCV({request:req('/api/cv/en'),env})).status,200);
 assert.equal((await setAccess({request:req('/api/admin/cv-access','PUT',{code:'correct-code-123'},true),env})).status,200);assert.equal((await setAccess({request:req('/api/admin/cv-access','PUT',{enabled:true},true),env})).status,200);assert.equal((await frenchCV({request:req('/api/cv'),env})).status,401);assert.equal((await englishCV({request:req('/api/cv/en'),env})).status,401);assert.equal((await unlock({request:req('/api/cv/unlock','POST',{code:'wrong-code-123'}),env})).status,401);
 const good=await unlock({request:req('/api/cv/unlock','POST',{code:'correct-code-123'}),env});assert.equal(good.status,200);const cookie=good.headers.get('Set-Cookie').split(';')[0];assert.match(good.headers.get('Set-Cookie'),/Secure; HttpOnly; SameSite=Strict/);assert.equal((await frenchCV({request:req('/api/cv','GET',undefined,false,cookie),env})).status,200);assert.equal((await englishCV({request:req('/api/cv/en','GET',undefined,false,cookie),env})).status,200);
 const [name,token]=cookie.split('=');const parts=decodeURIComponent(token).split('.');const expired=`${name}=${parts[0]}.${Math.floor(Date.now()/1000)-1}.${parts[2]}`;assert.equal((await frenchCV({request:req('/api/cv','GET',undefined,false,expired),env})).status,401);
 assert.equal((await revoke({request:req('/api/admin/cv-access/revoke','POST',undefined,true),env})).status,200);assert.equal((await frenchCV({request:req('/api/cv','GET',undefined,false,cookie),env})).status,401);const next=await unlock({request:req('/api/cv/unlock','POST',{code:'correct-code-123'}),env});assert.equal(next.status,200);assert.equal((await setAccess({request:req('/api/admin/cv-access','PUT',{code:'new-correct-code'},true),env})).status,200);assert.equal((await frenchCV({request:req('/api/cv','GET',undefined,false,next.headers.get('Set-Cookie').split(';')[0]),env})).status,401);
 for(let i=0;i<5;i++)await unlock({request:req('/api/cv/unlock','POST',{code:'bad-code-'+'x'.repeat(10)}),env});assert.equal((await unlock({request:req('/api/cv/unlock','POST',{code:'new-correct-code'}),env})).status,429);assert.equal((await getAccess({request:req('/api/admin/cv-access','GET',undefined,true),env})).status,200);});
test('image signatures, upload/replacement/restore, bilingual alt and static fallback',async()=>{const {env,files}=await fixture();assert.equal(imageType(png,'image/png'),'image/png');assert.equal(imageType(webp,'image/webp'),'image/webp');assert.equal(imageType(png,'image/jpeg'),null);
 const key='hero.main';const send=async file=>{const f=new FormData();f.append('image',file);return putPhoto({request:req('/api/admin/media/hero.main','PUT',f,true),env,params:{key}});};assert.equal((await send(jpeg)).status,200);assert.equal(files.size,1);assert.equal((await publicPhoto({request:req('/api/media?key=hero.main'),env})).headers.get('Content-Type'),'image/jpeg');assert.equal((await patchPhoto({request:req('/api/admin/media/hero.main','PATCH',{altFr:'Portrait FR',altEn:'Portrait EN',position:'top'},true),env,params:{key}})).status,200);const row=await env.DB.prepare('SELECT * FROM media_overrides WHERE media_key=?').bind(key).first();assert.equal(row.alt_en,'Portrait EN');assert.equal(row.object_position,'top');assert.equal((await send(new File([png],'a.png',{type:'image/png'}))).status,200);assert.equal(files.size,1);assert.equal((await send(new File(['<svg/>'],'x.svg',{type:'image/svg+xml'}))).status,400);assert.equal((await send(new File([new Uint8Array(5*1024*1024+1)],'too-big.jpg',{type:'image/jpeg'}))).status,400);assert.equal((await deletePhoto({request:req('/api/admin/media/hero.main','DELETE',undefined,true),env,params:{key}})).status,200);assert.equal(await (await publicPhoto({request:req('/api/media?key=hero.main'),env})).text(),'static fallback');assert.equal((await publicPhoto({request:req('/api/media?key=invalid'),env})).status,404);});
test('CEP upload, protected publication, replacement and removal',async()=>{const {env}=await fixture();const upload=async()=>{const form=new FormData();form.append('cep',pdf);return putCep({request:req('/api/admin/cep','PUT',form,true),env});};assert.equal((await publicCep({request:req('/api/cep'),env})).status,404);assert.equal((await upload()).status,200);assert.equal((await publicCep({request:req('/api/cep'),env})).status,404);assert.equal((await setCep({request:req('/api/admin/cep/settings','PUT',{public:true,protected:false},true),env})).status,200);assert.equal((await publicCep({request:req('/api/cep'),env})).status,200);assert.equal((await upload()).status,200);assert.equal((await setCep({request:req('/api/admin/cep/settings','PUT',{public:true,protected:true},true),env})).status,400);await setAccess({request:req('/api/admin/cv-access','PUT',{code:'correct-code-123'},true),env});assert.equal((await setCep({request:req('/api/admin/cep/settings','PUT',{public:true,protected:true},true),env})).status,200);assert.equal((await publicCep({request:req('/api/cep'),env})).status,401);const token=(await unlock({request:req('/api/cv/unlock','POST',{code:'correct-code-123'}),env})).headers.get('Set-Cookie').split(';')[0];assert.equal((await publicCep({request:req('/api/cep','GET',undefined,false,token),env})).status,200);assert.equal((await deleteCep({request:req('/api/admin/cep','DELETE',undefined,true),env})).status,200);assert.equal((await publicCep({request:req('/api/cep'),env})).status,404);});
test('publication requires all explicit fields per language; export excludes sensitive values',async()=>{const {env,sqlite}=await fixture();const put=async language=>publication({request:req('/api/admin/publication','PUT',{language,section:'scenario_a',visible:true},true),env});assert.equal((await put('fr')).status,400);for(const k of ['title','description','interests','constraints','status'])sqlite.prepare('INSERT INTO content_overrides(language,content_key,value,updated_at) VALUES(?,?,?,unixepoch())').run('fr',`project.scenario_a.${k}`,`Custom ${k}`);assert.equal((await put('fr')).status,200);assert.equal((await put('en')).status,400);const data=await (await exportConfig({request:req('/api/admin/export','GET',undefined,true),env})).json();assert.equal(data.publicationFlags[0].visible,1);assert.ok(!JSON.stringify(data).includes('cv_access_digest'));assert.ok(!JSON.stringify(data).includes('SESSION_SECRET'));assert.ok(!JSON.stringify(data).includes('contact_messages'));});
test('server-side rewrite removes hidden drafts; published flags and media update per language',async()=>{
 const {env,sqlite,files}=await fixture();const original=globalThis.HTMLRewriter;const handlers=new Map();
 globalThis.HTMLRewriter=class{on(selector,handler){handlers.set(selector,handler);return this;}transform(response){return response;}};
 try{
 const response=()=>new Response('<html></html>',{headers:{'Content-Type':'text/html'}});
 await applyPresentation(response(),env,'fr');
 const publicationHandler=handlers.get('[data-publication-section]');
 const fake=key=>{const state={removed:false,hidden:true};return{state,getAttribute:()=>key,remove(){state.removed=true;},removeAttribute(attr){if(attr==='hidden')state.hidden=false;}};};
 let draft=fake('international_detail');publicationHandler.element(draft);assert.equal(draft.state.removed,true);
 sqlite.prepare("INSERT INTO publication_flags VALUES('fr','international_detail',1,unixepoch())").run();
 await applyPresentation(response(),env,'fr');draft=fake('international_detail');handlers.get('[data-publication-section]').element(draft);assert.equal(draft.state.hidden,false);
 await applyPresentation(response(),env,'en');draft=fake('international_detail');handlers.get('[data-publication-section]').element(draft);assert.equal(draft.state.removed,true);
 files.set('media/hero.main/unit',{bytes:new Uint8Array([255,216,255])});sqlite.prepare("INSERT INTO media_overrides(media_key,r2_key,mime_type,size,alt_fr,alt_en,object_position,updated_at) VALUES('hero.main','media/hero.main/unit','image/jpeg',3,'FR alt','EN alt','top',unixepoch())").run();
 await applyPresentation(response(),env,'en');const attrs={};const img={getAttribute:()=> 'hero.main',setAttribute(k,v){attrs[k]=v;},removeAttribute(k){attrs[k]=null;}};handlers.get('[data-media-key]').element(img);assert.equal(attrs.alt,'EN alt');assert.equal(attrs.src,'/api/media?key=hero.main');assert.equal(attrs.srcset,null);assert.equal(attrs.style,'object-position: top');
 }finally{globalThis.HTMLRewriter=original;}
});
test('middleware blocks media routes when site is private',async()=>{const {env,sqlite}=await fixture();sqlite.prepare("UPDATE settings SET value='false' WHERE key='site_public'").run();let reached=false;const result=await middleware({request:req('/api/media?key=hero.main'),env,next:()=>{reached=true;return publicPhoto({request:req('/api/media?key=hero.main'),env});}});assert.equal(result.status,404);assert.equal(reached,false);});
