import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {sha256Hex,readSetting} from '../functions/lib/security.js';
import {onRequestPut as updateContent} from '../functions/api/admin/content.js';
import {onRequestGet as getHistory} from '../functions/api/admin/history.js';
import {onRequestPost as restoreText} from '../functions/api/admin/history/restore.js';
import {onRequestPost as createGrant,onRequestGet as listGrants} from '../functions/api/admin/access.js';
import {onRequestDelete as revokeGrant} from '../functions/api/admin/access/[hash].js';
import {onRequestGet as visitGrant} from '../functions/access/[token].js';
import {onRequestGet as grantStatus} from '../functions/api/access/status.js';
import {onRequestGet as frCV} from '../functions/api/cv.js';
import {onRequestGet as enCV} from '../functions/api/cv/en.js';
import {onRequestGet as cepPDF} from '../functions/api/cep.js';
import {onRequestGet as getSkills,onRequestPut as updateSkills} from '../functions/api/admin/skills.js';
import {onRequestGet as exportData} from '../functions/api/admin/export.js';
import {onRequestPost as previewImport} from '../functions/api/admin/import/preview.js';
import {onRequestPost as applyImport} from '../functions/api/admin/import/apply.js';
import {onRequest as middleware} from '../functions/_middleware.js';
import {applyPresentation} from '../functions/lib/presentation.js';
const origin='https://portfolio.example';
const schema=readFileSync(new URL('../schema.sql',import.meta.url),'utf8');
async function fixture(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(schema);
 sqlite.prepare("UPDATE settings SET value='true' WHERE key='site_public'").run();
 sqlite.prepare('INSERT INTO admin_sessions VALUES(?,?,?)').run(await sha256Hex('v9-session'),Math.floor(Date.now()/1000)+3600,1);
 const DB={prepare(sql){const st=sqlite.prepare(sql);let args=[];return {bind(...values){args=values;return this;},async first(){return st.get(...args)||null;},async all(){return {results:st.all(...args)};},async run(){return st.run(...args);}};},async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
 const files=new Map();const CV_BUCKET={async get(key){return files.has(key)?{body:files.get(key),writeHttpMetadata(){}}:null;},async head(key){return files.has(key)?{size:files.get(key).length}:null;},async put(key,bytes){files.set(key,bytes);},async delete(key){files.delete(key);}};
 const env={DB,CV_BUCKET,SESSION_SECRET:'test-v9-session-secret'};
 return {sqlite,files,env};
}
function req(path,method='GET',body,admin=false,cookie=''){const headers={Origin:origin,...(admin?{Cookie:'__Host-pm_admin=v9-session'}:{}),...(cookie?{Cookie:cookie}:{})};if(body!==undefined)headers['Content-Type']='application/json';return new Request(origin+path,{method,headers,...(body!==undefined?{body:JSON.stringify(body)}:{})});}
const json=(response)=>response.json();
test('V9 migration repeats without changing V8 data or sessions',async()=>{const {sqlite}=await fixture();sqlite.prepare("INSERT INTO content_overrides VALUES('fr','hero.title','Untouched',unixepoch())").run();const migration=readFileSync(new URL('../migrations/0009_editorial_access_history.sql',import.meta.url),'utf8');sqlite.exec(migration);sqlite.exec(migration);assert.equal(sqlite.prepare("SELECT value FROM content_overrides WHERE content_key='hero.title'").get().value,'Untouched');assert.equal(sqlite.prepare('SELECT count(*) n FROM admin_sessions').get().n,1);for(const name of ['skills_overrides','access_grants','admin_audit','media_overrides'])assert.ok(sqlite.prepare('SELECT name FROM sqlite_master WHERE name=?').get(name));});
test('bilingual layout includes two mobility columns, five linked skills and language roles',()=>{for(const file of ['../index.html','../en/index.html']){const page=readFileSync(new URL(file,import.meta.url),'utf8');assert.match(page,/class="mobility-lead"/);assert.match(page,/class="mobility-aside"/);assert.equal((page.match(/class="language-card"/g)||[]).length,3);assert.equal((page.match(/class="skill-card"/g)||[]).length,5);assert.equal((page.match(/class="case-study"/g)||[]).length,3);assert.match(page,/data-content-key="project\.timeline\.step_2\.title"/);assert.match(page,/data-last-updated/);for(const id of ['projects-palaminy','projects-fos','projects-substation'])assert.match(page,new RegExp(`id="${id}"`));}});
test('skill evidence accepts only whitelisted anchors and visibility per language',async()=>{const {env}=await fixture();const get=async language=>json(await getSkills({request:req(`/api/admin/skills?language=${language}`,'GET',undefined,true),env}));assert.equal((await get('fr')).items.length,5);assert.equal((await get('en')).items[0].visible,true);let response=await updateSkills({request:req('/api/admin/skills','PUT',{language:'fr',key:'protection',visible:false,proofs:['field-inspection']},true),env});assert.equal(response.status,200);assert.deepEqual((await get('fr')).items[0].proofs,['field-inspection']);assert.equal((await get('fr')).items[0].visible,false);assert.equal((await get('en')).items[0].visible,true);response=await updateSkills({request:req('/api/admin/skills','PUT',{language:'fr',key:'protection',visible:true,proofs:['https://evil.example']},true),env});assert.equal(response.status,400);response=await updateSkills({request:req('/api/admin/skills','PUT',{language:'fr',key:'protection',visible:true,proofs:['field-inspection']},false),env});assert.equal(response.status,401);});
test('temporary grant is random, hashed, scoped, expiring and revocable without altering CV code',async()=>{const {env,sqlite,files}=await fixture();sqlite.prepare("UPDATE settings SET value='true' WHERE key IN ('cv_available','cv_en_available','cep_available','cv_access_enabled')").run();files.set('cv-pm-systems-engineering.pdf',new Uint8Array([37,80,68,70,45]));files.set('cv-pm-systems-engineering-en.pdf',new Uint8Array([37,80,68,70,45]));files.set('cep-presentation.pdf',new Uint8Array([37,80,68,70,45]));
 assert.equal((await createGrant({request:req('/api/admin/access','POST',{hours:24,fr:true,en:false,cep:true},false),env})).status,401);
 const created=await json(await createGrant({request:req('/api/admin/access','POST',{hours:24,fr:true,en:false,cep:true},true),env}));const token=created.url.split('/').at(-1);assert.match(token,/^[A-Za-z0-9_-]{43}$/);assert.equal(sqlite.prepare('SELECT count(*) n FROM access_grants WHERE token_hash=?').get(created.hash).n,1);assert.ok(!JSON.stringify(sqlite.prepare('SELECT * FROM access_grants').all()).includes(token));
 const visit=await visitGrant({request:req(`/access/${token}`),env,params:{token}});assert.equal(visit.status,303);assert.match(visit.headers.get('Set-Cookie'),/Secure; HttpOnly; SameSite=Lax/);assert.equal(visit.headers.get('Referrer-Policy'),'no-referrer');const cookie=visit.headers.get('Set-Cookie').split(';')[0];
 assert.deepEqual(await json(await grantStatus({request:req('/api/access/status','GET',undefined,false,cookie),env})),{fr:true,en:false,cep:true});assert.equal((await frCV({request:req('/api/cv','GET',undefined,false,cookie),env})).status,200);assert.equal((await enCV({request:req('/api/cv/en','GET',undefined,false,cookie),env})).status,401);assert.equal((await cepPDF({request:req('/api/cep','GET',undefined,false,cookie),env})).status,200);
 const all=await json(await listGrants({request:req('/api/admin/access','GET',undefined,true),env}));assert.ok(!JSON.stringify(all).includes(token));assert.equal((await revokeGrant({request:req(`/api/admin/access/${created.hash}`,'DELETE',undefined,true),env,params:{hash:created.hash}})).status,200);assert.equal((await frCV({request:req('/api/cv','GET',undefined,false,cookie),env})).status,401);assert.equal((await visitGrant({request:req(`/access/${token}`),env,params:{token}})).status,404);sqlite.prepare('UPDATE access_grants SET revoked_at=NULL,expires_at=unixepoch()-1 WHERE token_hash=?').run(created.hash);assert.equal((await visitGrant({request:req(`/access/${token}`),env,params:{token}})).status,404);});
test('text changes keep previous value and restore rejects stale versions',async()=>{const {env}=await fixture();const key='hero.title';const update=async value=>updateContent({request:req('/api/admin/content','PUT',{language:'fr',key,value},true),env});assert.equal((await update('First changed title')).status,200);const first=(await json(await getHistory({request:req('/api/admin/history','GET',undefined,true),env}))).events.find(x=>x.item_key===key);assert.ok(first.previous_value);assert.equal(first.new_value,'First changed title');assert.equal((await update('Second title')).status,200);assert.equal((await restoreText({request:req('/api/admin/history/restore','POST',{id:first.id},true),env})).status,409);const current=(await json(await getHistory({request:req('/api/admin/history','GET',undefined,true),env}))).events.find(x=>x.item_key===key&&x.new_value==='Second title');assert.equal((await restoreText({request:req('/api/admin/history/restore','POST',{id:current.id},true),env})).status,200);assert.equal((await env.DB.prepare('SELECT value FROM content_overrides WHERE language=? AND content_key=?').bind('fr',key).first()).value,'First changed title');});
test('import previews diff, requires confirmation and never imports credentials, grants or binaries',async()=>{const {env,sqlite}=await fixture();const backup=await json(await exportData({request:req('/api/admin/export','GET',undefined,true),env}));backup.contentOverrides=[{language:'fr',content_key:'hero.title',value:'Restored title',updated_at:0}];backup.settings.linkedin_url='https://www.linkedin.com/in/example';backup.settings.cv_access_digest='UNSAFE-DO-NOT-IMPORT';backup.mediaMetadata=[{media_key:'hero.main',alt_fr:'FR',alt_en:'EN',object_position:'top',r2_key:'media/evil'}];backup.skillsOverrides=[{language:'en',skill_key:'automation',proofs_json:'["projects-palaminy"]',visible:1}];let response=await previewImport({request:req('/api/admin/import/preview','POST',{data:backup},true),env});assert.equal(response.status,200);const plan=await json(response);assert.equal(plan.summary.texts,1);assert.equal(plan.summary.photos,1);assert.equal((await applyImport({request:req('/api/admin/import/apply','POST',{data:backup,digest:plan.digest,confirm:false},true),env})).status,400);response=await applyImport({request:req('/api/admin/import/apply','POST',{data:backup,digest:plan.digest,confirm:true},true),env});assert.equal(response.status,200);assert.equal((await env.DB.prepare('SELECT value FROM content_overrides WHERE content_key=?').bind('hero.title').first()).value,'Restored title');assert.equal((await readSetting(env.DB,'cv_access_digest')),'');assert.equal((await env.DB.prepare('SELECT r2_key FROM media_overrides WHERE media_key=?').bind('hero.main').first()).r2_key,null);assert.equal(sqlite.prepare('SELECT count(*) n FROM access_grants').get().n,0);
 backup.contentOverrides[0].value='Altered';assert.equal((await applyImport({request:req('/api/admin/import/apply','POST',{data:backup,digest:plan.digest,confirm:true},true),env})).status,409);backup.contentOverrides[0].content_key='not-whitelisted';assert.equal((await previewImport({request:req('/api/admin/import/preview','POST',{data:backup},true),env})).status,400);
});
test('private site blocks temporary access before token exchange',async()=>{const {env,sqlite}=await fixture();sqlite.prepare("UPDATE settings SET value='false' WHERE key='site_public'").run();let called=false;const result=await middleware({request:req('/access/'+'x'.repeat(43)),env,next(){called=true;return new Response('leak');}});assert.equal(result.status,404);assert.equal(called,false);});
test('HTML rewrite hides the fallback only for a published target and changes skill proofs safely',async()=>{
 const {env,sqlite}=await fixture();const before=globalThis.HTMLRewriter,handlers=new Map();
 globalThis.HTMLRewriter=class{on(selector,handler){handlers.set(selector,handler);return this;}transform(response){return response;}};
 try{
 const response=()=>new Response('<html></html>',{headers:{'Content-Type':'text/html'}});
 await applyPresentation(response(),env,'fr',req('/'));let removed=false;
 handlers.get('[data-publication-placeholder]').element({getAttribute:()=> 'international_detail',remove(){removed=true;}});assert.equal(removed,false);
 sqlite.prepare("INSERT INTO publication_flags VALUES('fr','international_detail',1,unixepoch())").run();
 sqlite.prepare("INSERT INTO skills_overrides VALUES('fr','automation','[\"projects-fos\"]',1,unixepoch())").run();
 await applyPresentation(response(),env,'fr',req('/'));handlers.get('[data-publication-placeholder]').element({getAttribute:()=> 'international_detail',remove(){removed=true;}});assert.equal(removed,true);
 let markup=null;handlers.get('[data-skill-key] .skill-proofs').element({getAttribute:()=> 'automation',setInnerContent(value){markup=value;}});assert.match(markup,/href="#projects-fos"/);assert.doesNotMatch(markup,/projects-palaminy/);
 let date=null;handlers.get('[data-last-updated]').element({setInnerContent(value){date=value;}});assert.match(date,/Dernière mise à jour :/);
 await applyPresentation(response(),env,'en',req('/en/'));removed=false;handlers.get('[data-publication-placeholder]').element({getAttribute:()=> 'international_detail',remove(){removed=true;}});assert.equal(removed,false);
 }finally{globalThis.HTMLRewriter=before;}
});
